### PR TITLE
feat: compute registry data

### PR DESCRIPTION
**Pull request by Sekhmet**
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/485
Depends on: https://github.com/snapshot-labs/snapshot.js/pull/1050

This PR adds compute function that creates delegation data for delegateRegistryV1.

### Test plan

1. Run this project
2. Run [this query](http://localhost:3000/?variables=%7B%0A%20%20%22id%22%3A%20%22apecoin.eth%22%0A%7D&query=query%20Test(%24id%3A%20String!)%20%7B%0A%20%20governance(id%3A%20%24id)%20%7B%0A%20%20%20%20id%0A%20%20%20%20currentDelegates%0A%20%20%20%20totalDelegates%0A%20%20%20%20delegatedVotes%0A%20%20%20%20delegatedVotesRaw%0A%20%20%7D%0A%20%20delegates%20(where%3A%20%7B%20governance%3A%20%24id%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20delegatedVotes%0A%20%20%20%20tokenHoldersRepresentedAmount%0A%20%20%7D%0A%7D%0A).
3. It will return empty response (because we don't wait for data to be computed, only return stored value).
4. See in logs that computation was started, wait for it to finish.
5. Repeat the request.
6. You see values and they are correct (compare with https://snapshot.org/#/delegate/apecoin.eth)

Query:
```gql
query Test($id: String!) {
  governance(id: $id) {
    id
    currentDelegates
    totalDelegates
    delegatedVotes
    delegatedVotesRaw
  }
  delegates (where: { governance: $id}) {
    id
    delegatedVotes
    tokenHoldersRepresentedAmount
  }
}

```

### CODE REVIEW

**Comment by bonustrack** [comment]
Can you add something like this in index.ts, it wont work for me and on DigitalOcean without it.
```
if (process.env.CA_CERT) {
  process.env.CA_CERT = process.env.CA_CERT.replace(/\\n/g, '\n');
}
```

**Comment by bonustrack** [comment]
It seem that we can only trigger a single space computation at once, if I try to query for apecoin.eth then safe.eth I only see console log for apecoin.eth, this will be a blocker for production use.

**Comment by bonustrack** [comment]
Just tested with multiple space, it works well so far. I think we will be missing many delegates because:
1: The delegate registry allows for global delegation, I think currently you only gather delegation for specific space
2: There is also plenty of users with voting power that did not delegated their voting power, but still should appear on delegate leaderboard. "delegation" strategy give you voting power even if you dont delegate to yourself.
Would be great to have the first one, the second one would be more tricky we can skip for next cycle, it will requires querying for voters.

**Comment by bonustrack** [comment]
FYI: I've already setup an app on DigitalOcean with a Postgres db and proper env

**Comment by Sekhmet** [comment]
Added support for global delegation, needs update in snapshot.js: https://github.com/snapshot-labs/snapshot.js/pull/1050

**Comment by Sekhmet** [comment]
https://delegate-registry-api-46t6m.ondigitalocean.app/?operationName=Test&query=query%20Test(%24id%3A%20String!)%20%7B%0A%20%20governance(id%3A%20%24id)%20%7B%0A%20%20%20%20id%0A%20%20%20%20currentDelegates%0A%20%20%20%20totalDelegates%0A%20%20%20%20delegatedVotes%0A%20%20%20%20delegatedVotesRaw%0A%20%20%7D%0A%20%20delegates%20(where%3A%20%7B%20governance%3A%20%24id%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20delegatedVotes%0A%20%20%20%20tokenHoldersRepresentedAmount%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22id%22%3A%20%22apecoin.eth%22%0A%7D

Seems to be working.

**Pull request merged**
